name: edagang
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.2
  cupertino_icons: ^1.0.3
  flutter_swiper : ^1.1.6
  flutter_html: ^2.1.0
  scoped_model: ^1.1.0
  http: ^0.13.3
  dio: ^4.0.0
  intl: ^0.17.0
  google_fonts: ^2.1.0
  #loading_gifs: ^0.3.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^2.0.9
  flutter_staggered_grid_view: ^0.4.0
  date_format: ^2.0.2
  photo_view: ^0.11.1
  page_indicator: ^0.4.1
  fluttertoast: ^8.0.7
  badges: ^2.0.1
  flutter_share: ^2.0.0
  path_provider: ^2.0.2
  onesignal_flutter: ^3.0.0
  google_sign_in: ^5.0.4
  flutter_facebook_login: ^3.0.0
  intro_slider: ^3.0.2
  device_id: ^0.2.0
  #ff_navigation_bar: ^0.1.5
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.0.9
  huawei_push: ^5.1.1+301
  shimmer: ^2.0.0
  #carousel_slider: ^4.0.0
  line_awesome_icons: ^1.0.4+2
  firebase_analytics: ^8.1.2
  firebase_dynamic_links: ^2.0.6
  native_updater: ^0.1.0
  equatable: ^2.0.3
  dartz: ^0.9.2
  share: ^2.0.4
  #flutter_link_preview: ^1.5.6


flutter_icons:
  image_path: "assets/icons/ic_launcher_new.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/icons/

fonts:
    - family: EdagangIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic